jwt.secret: '9AEW57AzDzHiamTadS3Nzal28MP1yo9bkwlqBmeUj27POsBleTfvhb7YzMxA2q+0/xJEsx7RpYRorLUDEUugrQ=='
jwt.access.token.validity: 360000000
jwt.refresh.token.validity: 8640000000
email.name: 'nmhahalo2000@gmail.com'
email.password: 'vcgqhgrykgbaqyck'
base.api: '/api/v1'
domain: 'https://54.179.82.237'
domain1: 'http://localhost:3000'
domain2: 'https://13.213.53.246'
domain3: 'https://benshop.online'
domain4: 'http://54.179.82.237'
domain5: 'http://13.213.53.246'
domain6: 'http://benshop.online'
root.directory: 'C:/Users/Administrator/Desktop/apache-tomcat-8.5.77/webapps'
root.directory1: 'C:'
subfolder.product.image: '/product/image'
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

